### ISSUE TITLE
Multi-threading for autoindex.py possible?

### ISSUE THREAD

**Issue by kopeckyf** [langsci/pypi#11]
For some time later: Can we enable Multi-threading on autoindex.py? For example, each thread could run on one chapter file

**Comment by Glottotopia** [comment]
On a sample project (Velar Fronting), autoindexing with 5 threads takes 33 seconds. With 1 thread (or without multithreading) it takes 22 seconds, with 2 threads 25 seconds. 
There is thus no gain in using multithreading.
