### ISSUE TITLE
doc2tex conversion failes when document is in .doc format, but not in others

### ISSUE THREAD

**Issue by kopeckyf** [langsci/pypi#14]
Documents are not converted to LaTeX when they are submitted in .doc (Word 97-2003) format, but the same documents are converted successfully when they are submitted in .docx or .odt format. The source software is LibreOffice 7 in all cases. It's not clear whether the problem occurs with exports from MS Word.

**Comment by Glottotopia** [comment]
deprecated conversion of doc since this is not a very important format. These days, most people should have docx available.
