### ISSUE TITLE
Extra commas in bib normalisation

### ISSUE THREAD

**Issue by kopeckyf** [langsci/pypi#15]
With wrapperscripts/normalizebib.py, some entries receive double commas at the end of single lines, often the `page` line. This induces a syntax error. The cause is probably in trailing commas at the end of entries.

Example of bug:
```
pages = {9--16},,
```

**Comment by mstelling** [comment]
yeah, there was such a diversity of syntax problems in the bib files that I kept rerunning the script, fixing errors as I went. There's probably a better solution, probably involving making a list of common errors and looking for them.
