### ISSUE TITLE
Error in registering a chapter with no abstract to zenodo

### ISSUE THREAD

**Issue by kopeckyf** [langsci/pypi#16]
Entries with a `description` of less than 400 characters are rejected by the Zenodo API. 

One workaround is to temporarily insert an `\abstract{}` into the offending chapter, e.g.

```latex
\abstract{This is the preface to the volume VOLUMETITLE.}
```

But maybe there is another solution.

**Comment by Glottotopia** [comment]
are you sure that the limit is 400? I am pretty certain I have uploaded texts like "replace this dummy abstract on Zenodo" via the API, which is much shorter than 400 characters

**Comment by kopeckyf** [comment]
Indeed, I can't remember where the 400 comes from. It definitely works to send an abstract to Zenodo with `This is the preface to the volume VOLUMETITLE.` even if the resulting char count is less than 400.

**Comment by kopeckyf** [comment]
.... But this doesn't solve this issue. The problem remains that one has to manually insert a dummy abstract that is not used in the chapter, but only on Zenodo. 

But maybe the only solution would be to convince Zenodo to accept chapters without abstract. Maybe that's a long shot.

**Comment by Glottotopia** [comment]
I think there is a difference between `\abstract{}` and ` ` (nothing). One of them should work, but I can't remember which one. 
I think it is OK that the program complains when there is no information about an abstract at all. Positive information `\noabstract` is useful, as it shows that there is intentionally no abstract.
