### ISSUE TITLE
Importing error with pyglottolog

### ISSUE THREAD

**Issue by kopeckyf** [langsci/pypi#18]
When importing the module `pyglottolog` in `zenodo.py`, the line 
https://github.com/langsci/pypi/blob/67183e1d7b067ee81e092bc05f62fe6559168d28/langsci/langsci/zenodo.py#L12

is responsible for an error. Apparently, a dictionary  `trees` is missing? The script seems to work fine when the line is deleted.

**Comment by Glottotopia** [comment]
you have to clone the glottolog data. See https://pypi.org/project/pyglottolog/. This yields a directory `trees`. Probably, that directory should have a specified location on your hard disk, to which you symlink. 

There might be more convenient setups for this.

**Comment by Glottotopia** [comment]
The script now tries to instantiate `Glottolog('.' )`. If that fails, Glottocodes will be ignored for this book project.
