### ISSUE TITLE
Page numbers in citations come out after \cite command

### ISSUE THREAD

**Issue by stefan11** [langsci/pypi#22]
attested (cf. Weggelaar 1986: 304).  ist translated into: (cf. \citealt{Weggelaar1986}: 304).

The page number could be given as argument to \citealt

Further examples:

(see \citealt{FleischerBarz2012}, ch. 5.2–5.3, and \citealt{Elsen2014}: 215–222

**Comment by Glottotopia** [comment]
fixing this will be error-prone and only have little benefit over the current solution.
