### ISSUE TITLE
bib converter does not recognize more than two authors/editors

### ISSUE THREAD

**Issue by Lu-Yanru** [langsci/pypi#26]
Only the "&" symbol is converted into "and" in the entry "author" or "editor", but not the commas between the names. As a result, the citation key is generated as a combination of the surnames of the first and last authors instead of "EtAl".

Examples:

Bastin, Yvonne, André Coupez & Michael Mann. 1999. Continuity and Divergence in the Bantu Languages: Perspectives from a lexicostatistic study (Annals - Human Sciences 162). Tervuren: Royal Museum for Central Africa.
```
@book{BastinMann1999,
	address = {Tervuren},
	author = {Bastin, Yvonne, André Coupez and Michael Mann},
	number = {162},
	publisher = {Royal Museum for Central Africa},
	series = {Annals - Human Sciences},
	sortname = {Bastin, Yvonne, Andre Coupez and Michael Mann},
	title = {Continuity and Divergence in the {Bantu} Languages: {{P}}erspectives from a lexicostatistic study},
	year = {1999}
}
```

Gibson, Hannah C., Rozenn Guérois & Lutz Marten. 2019. Variation in Bantu copula constructions. In María J. Arche, Antonio Fábregas & Rafael Marín (eds.), The grammar of copulas across languages (Oxford Studies in Theoretical Linguistics 73), 213–242. New York, NY: Oxford University Press.
```
@incollection{GibsonMarten2019,
	address = {New York, NY},
	author = {Gibson, Hannah C., Rozenn Guérois and Lutz Marten},
	booktitle = {The grammar of copulas across languages ({Oxford} Studies in Theoretical Linguistics 73)},
	editor = {María J. Arche, Antonio Fábregas and Rafael Marín},
	pages = {213–242},
	publisher = {Oxford University Press},
	sortname = {Gibson, Hannah C., Rozenn Guerois and Lutz Marten},
	title = {Variation in {Bantu} copula constructions},
	year = {2019}
}
```

**Comment by Glottotopia** [comment]
for strings like 
```
editor = {María J. Arche, Antonio Fábregas and Rafael Marín},
```
it is difficult to know what the first names and the last names are. It could be that there is someone called "{Antonio Fábregas} {María J. Arche}" and that this work would be a two-author work. Compare "{Sabine Maria} {Schulte im Walde}" from "Schulte im Walde, Sabine Maria". 
The converter could try some heuristics, but it will be subtly wrong in an non-neglectable number of cases, so it is better to leave this error as it is, which will mean that a human will eventually have a look to fix it.
